server:
  servlet:
    context-path: /dmtp-gateway
  port: 8085

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"

spring:
  profiles:
    active: docker
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: dmtp-gateway

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: ${spring.application.name}:${server.port}
        url: http://spring-boot-admin:8088/spring-boot-admin

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: dmtp-services
            client-secret: AHfsvRKHDPMfs8tu6c8vRoL2CfxEu29f
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/dmtp-gateway
            authorization-uri: http://keycloak:8080/realms/dmtp-gateway/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/dmtp-gateway/protocol/openid-connect/token

  cloud:
    gateway:
      routes:
        - id: dmtp-server
          uri: http://dmtp-server:8084
          predicates:
            - Path=/dmtp-server/**
        - id: fi-integration
          uri: http://fi-integration:8081
          predicates:
            - Path=/fi-integration/**
        - id: transfer-repository
          uri: http://transfer-repository:8083
          predicates:
            - Path=/transfer-repository/**
        - id: validation-server
          uri: http://validation-server:8090
          predicates:
            - Path=/validation-server/**
        - id: mock-mts
          uri: http://mock-mts:8086
          predicates:
            - Path=/mock-mts/**

springdoc:
  swagger-ui:
    path: /dmtp-gateway/swagger-ui.html
    use-root-path: true
    urls:
      - name: dmtp-server
        url: http://localhost:8085/dmtp-server/v3/api-docs
      - name: fi-integration
        url: http://localhost:8085/fi-integration/v3/api-docs
      - name: transfer-repository
        url: http://localhost:8085/transfer-repository/v3/api-docs
      - name: validation-server
        url: http://localhost:8085/validation-server/v3/api-docs
      - name: mock-mts
        url: http://localhost:8085/mock-mts/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/dmtp-gateway/actuator"
  endpoint:
    health:
      show-details: always