CREATE TABLE IF NOT EXISTS VALIDATION_SCHEMA.BLACKLISTED_USERS
(
    ID              BIGSERIAL PRIMARY KEY,
    FIRST_NAME      VARCHAR(20)   NOT NULL,
    LAST_NAME       VARCHAR(30)   NOT NULL,
    PERSONAL_NUMBER BIGINT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS VALIDATION_SCHEMA.TRANSFER_LIMITS
(
    ID              BIGSERIAL PRIMARY KEY,
    TRANSFER_TYPE   VARCHAR(10) NOT NULL,
    MTS             VARCHAR(30) NOT NULL,
    COUNTRY         VARCHAR(3)  NOT NULL,
    CURRENCY        VARCHAR(3)  NOT NULL,
    MIN_AMOUNT      BIGINT      NOT NULL,
    MAX_AMOUNT      BIGINT      NOT NULL
);