INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('*', 'moneygram', '*', '*', 1, 15000);

INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('SEND', '*', '*', 'USD', 1, 5000);

INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('SEND', '*', '*', 'GEL', 1, 15000);

INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('SEND', '*', 'GEO', 'GEL', 1, 30000);

INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('RECEIVE', '*', '*', 'USD', 1, 5000);

INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('RECEIVE', '*', '*', 'GEL', 1, 15000);

INSERT INTO VALIDATION_SCHEMA.TRANSFER_LIMITS (TRANSFER_TYPE, MTS, COUNTRY, CURRENCY, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('RECEIVE', '*', 'GEO', 'USD', 1, 10000);
