server:
  servlet:
    context-path: /validation-server
  port: 8090

spring:
  config:
    activate:
      on-profile: local, test
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: validation-server
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    default-schema: validation_schema
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      group-id: validation-server-group
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: ${spring.application.name}:${server.port}
        url: http://localhost:8088/spring-boot-admin
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:VALIDATION_SERVER
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

openapi:
  servers: http://localhost:8085/validation-server
