CREATE TABLE IF NOT EXISTS BANK_SERVICE_SCHEMA.CLIENTS
(
    ID              BIGINT DEFAULT NEXTVAL('BANK_SERVICE_SCHEMA.BANK_SERVICE_GLOBAL_SEQUENCE') PRIMARY KEY,
    FIRST_NAME      VARCHAR(20)   NOT NULL,
    LAST_NAME       VARCHAR(30)   NOT NULL,
    PERSONAL_NUMBER BIGINT UNIQUE NOT NULL,
    EMAIL           VARCHAR(50)   NOT NULL,
    PHONE           VARCHAR(20)   NOT NULL,
    ADDRESS         VARCHAR(200)  NOT NULL,
    CITIZENSHIP     VARCHAR(50)   NOT NULL,
    CLIENT_STATUS   VARCHAR(15)   NOT NULL,
    DATE_OF_BIRTH   DATE          NOT NULL
);

CREATE TABLE IF NOT EXISTS BANK_SERVICE_SCHEMA.ACCOUNTS
(
    ID             BIGINT DEFAULT NEXTVAL('BANK_SERVICE_SCHEMA.BANK_SERVICE_GLOBAL_SEQUENCE') PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CURRENCY       VARCHAR(50)        NOT NULL,
    STATUS         VARCHAR(15)        NOT NULL,
    BALANCE        DECIMAL            NOT NULL,
    CLIENT_ID      BIGINT             NOT NULL
);

CREATE TABLE IF NOT EXISTS BANK_SERVICE_SCHEMA.TRANSACTIONS
(
    ID                  BIGINT DEFAULT NEXTVAL('BANK_SERVICE_SCHEMA.BANK_SERVICE_GLOBAL_SEQUENCE') PRIMARY KEY,
    SENDER_ACCOUNT_ID   BIGINT      NOT NULL,
    RECEIVER_ACCOUNT_ID BIGINT      NOT NULL,
    STATUS              VARCHAR(15) NOT NULL,
    CREATION_DATE       TIMESTAMP   NOT NULL,
    AMOUNT              DECIMAL     NOT NULL,
    CURRENCY            VARCHAR(3)  NOT NULL
);