INSERT INTO BANK_SERVICE_SCHEMA.CLIENTS (FIRST_NAME, LAST_NAME, PERSONAL_NUMBER, EMAIL, PHONE, ADDRESS, CITIZENSHIP, CLIENT_STATUS, DATE_OF_BIRTH)
VALUES ('TRANSFER', 'SYSTEM', '19001111777', 'luka.mebonia@azry.com', '555-555-555', 'Tbilisi, Georgia', 'Georgia', 'ACTIVE', '1990-01-01');
