CREATE TABLE IF NOT EXISTS BANK_SERVICE_SCHEMA.USERS
(
    ID       BIGINT DEFAULT NEXTVAL('BANK_SERVICE_SCHEMA.BANK_SERVICE_GLOBAL_SEQUENCE') PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100)       NOT NULL
);

INSERT INTO BANK_SERVICE_SCHEMA.USERS (USERNAME, PASSWORD)
VALUES ('admin', '$2a$10$hlPj9QAnq/uEekK5jQT58ugWRdMv1MyGcgpkqOSB4zdSJPjYpcFYC');
INSERT INTO BANK_SERVICE_SCHEMA.USERS (USERNAME, PASSWORD)
VALUES ('LukaMebonia', '$2a$10$wpCXZpLFVV4xMAt/y8Zg3.j56z9s7ijLD1BdYmnFW5LTNwROv/iVa');
INSERT INTO BANK_SERVICE_SCHEMA.USERS (USERNAME, PASSWORD)
VALUES ('GiorgiJanashvili', '$2a$10$MizLbN7vNK8QcnP.OKPitOEOcxjb/DXnDZP9vv9FVOEpSSW0JGvRS');
INSERT INTO BANK_SERVICE_SCHEMA.USERS (USERNAME, PASSWORD)
VALUES ('TamtaGiorgadze', '$2a$10$VXDx/m24OEXbdKE4U8ioNeEjaOHy9OaM0.p6xmD6lB0Fz7p0f49gW');