server:
  servlet:
    context-path: /bank-service
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: bank-service
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        current_session_context_class: thread
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    default-schema: bank_service_schema

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:BANK_SERVICE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

bank-service:
  currencies:
    - GEL
    - EUR
    - GBP
    - USD


  transaction-success-percentage: 90
  transaction-scheduling-initialDelay: 10000
  transaction-scheduling-fixedRate: 10000

  blacklisted-countries:
    - Russia
    - Venezuela
    - Nicaragua
    - Nauru
    - Syria
    - Belarus

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/dmtp
    username: postgres
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:BANK_SERVICE
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect