apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - datasourceName: Tempo
          datasourceUid: tempo
          matcherType: label
          name: traceid
          matcherRegex: traceid
          url: $${__value.raw}
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    version: 1
    editable: false
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        customQuery: true
        query: '{exporter="OTLP"} | json | traceid=`$${__span.traceId}`'
        tags: [ { key: 'service.name', value: 'job' } ]

