server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:

    otlp:
      protocols:
        http:
        grpc:

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
