server:
  servlet:
    context-path: /mock-mts
  port: 8086

spring:
  config:
    activate:
      on-profile: local, test
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: mock-mts
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      group-id: mock-mts-group
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: ${spring.application.name}:${server.port}
        url: http://localhost:8088/spring-boot-admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

openapi:
  servers: http://localhost:8085/mock-mts




